app/modules/pages/urls.py
from django.conf.urls import include, url

from app.modules.pages.views import *


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
]

app/modules/posts/urls.py
from django.conf.urls import include, url

from app.modules.posts.views import *


urlpatterns = [
    url(r'^(?P<slug>[-\w]+)/$', PostView.as_view(), name='post'),
    url(r'^tag/(?P<tag>[-\w]+)/$', PostsTagView.as_view(), name='posts-tag'),
]

app/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^', include('app.modules.pages.urls', namespace='pages')),
    url(r'^posts/', include('app.modules.posts.urls', namespace='posts')),

    url(r'^admin/', include(admin.site.urls)),
]

app/models.py
from django.core.urlresolvers import reverse_lazy as reverse 
from django.db import models


class Post(models.Model):

    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    tags = models.CharField(max_length=250)

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.__str__()

    def get_absolute_url(self):
        return reverse('posts:post', kwargs={ 'slug': self.slug })

    @property
    def tag_list(self):
        return self.tags.split(',')

app/modules/pages/views.py
from django.views.generic import TemplateView

from app.models import *


class HomeView(TemplateView):
    template_name = 'pages/home.html'

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)

        context['posts'] = Post.objects.order_by('-date_posted')

        return context

app/modules/posts/views.py
from django.conf import settings
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import TemplateView

from app.models import *


class PostView(TemplateView):
    template_name = 'posts/post.html'

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)

        context['post'] = get_object_or_404(Post, slug=kwargs.get('slug'))

        context['disqus_shortname'] = settings.DISQUS_SHORTNAME

        return context

class PostsTagView(TemplateView):
    template_name = 'pages/home.html'

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)

        context['tag'] = kwargs.get('tag','').lower()

        context['posts'] = Post.objects.filter(
        	tags__contains=context['tag']).order_by('-date_posted')

        return context

app/templates/base.html
{% load i18n %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>JuaniFioren</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/site.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/syntaxhighlight.css' %}">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

    <div class="sidebar">
        <div class="first">
            <h1>Juan Ignacio Fiorentino</h1>
            <h2>passionate web developer</h2>
        </div>
        <div class="second">
            <ul class="menu">
                <li><a href="{% url 'pages:home' %}">Home</a></li>
                <li><a href="#">About</a></li>
            </ul>
        </div>
        <img src="https://avatars3.githubusercontent.com/u/5168681?v=3&s=460">
    </div>

    <div class="content">
        <div class="content-wrapper">

            {% block content %}{% endblock %}
            
            <div class="footer">
                <p><a href="https://github.com/juanifioren/juanifioren-com" target="_BLANK">Like this site? See the source code here.</a> <a href="https://www.djangoproject.com/" target="_BLANK">Built with Django</a>.</p>
            </div>
            
        </div>
    </div>

    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/site.js' %}"></script>

</body>
</html>

app/templates/pages/home.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

    {% if tag %}
    <div class="post-date">Posts with tag "{{ tag }}"</div>
    {% endif %}

    {% for post in posts %}
    <h1><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h1>
    <span>{{ post.date_posted | date:"l, d M Y" }}.</span>
    <span>Tags: 
    {% for tag in post.tag_list %}
    <a href="{% url 'posts:posts-tag' tag %}"><strong>{{ tag | upper }}</strong></a>
    {% endfor %}
    </span>

    {% if not forloop.last %}
    <hr>
    {% endif %}
    {% empty %}
    <p>No posts yet! Create your first one <a href="{% url 'admin:index' %}">here</a></p>
    {% endfor %}

{% endblock %}

app/templates/posts/post.html
{% extends "base.html" %}
{% load i18n %}
{% load markdown_tags %}

{% block content %}

    <h1 class="post-title">{{ post.title }}</h1>
    <div class="post-date">Posted on {{ post.date_posted | date:"l, d M Y" }}.</div>
    <p>{{ post.content | markdownify | safe }}</p>
    <ul class="post-tags">
        {% for tag in post.tag_list %}
        <li><a href="{% url 'posts:posts-tag' tag %}">{{ tag | upper }}</a></li>
        {% endfor %}
    </ul>

    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES * * */
        var disqus_shortname = "{{ disqus_shortname }}";
        
        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

{% endblock %}